### ISSUE TITLE
Hacer un ejemplo de un POST

### ISSUE THREAD

**Issue by jriverac** [jriverac/JSON-Fun#3]
El objetivo es poder introducir una cadena en la app y mandar esa cadena a un recurso web y que el recurso lo reconozca y lo procese para crear un registro.

Este es el endpoint para que envies tu request de GET:
`http://chupes.herokuapp.com/contacts.json`

Este es para el POST:
`http://chupes.herokuapp.com/contacts.json`

Este es un ejemplo de como crear un registro:
```
curl -X "POST" "http://chupes.herokuapp.com/contacts.json" \
     -H "Content-Type: application/json" \
     -d $'{
  "contact": {
    "email": "laurentino@elchupes.com",
    "name": "Laurentis"
  }
}'

```

**Comment by jriverac** [comment]
@LaurentinoMX, que tal te fue con esta onda? Ya pudiste hacer un post?

**Comment by LaurentinoMX** [comment]
No chief, osea ya vi como y baje un codigo pero no lo he revisado a fondo, el dia de hoy andare de peda pero mañana lo pruebo temprano, vtw esta chida su pagina serverlessly

**Comment by jriverac** [comment]
@LaurentinoMX échale ganas pues, para ir agregando el resto de las funciones en el server. 

Las acciones son:

* Index 
* show
* create
* update
* destroy

**Comment by jriverac** [comment]
@LaurentinoMX con madres! ya lo vi jalar en mi maquina, pero hiciste un desvergue con los commits. Vi que hasta hiciste hasta un push a origin master al final.
