### ISSUE TITLE
Hacer un ejemplo de un index (GET)

### ISSUE THREAD

**Issue by jriverac** [jriverac/JSON-Fun#5]
Una llamada a acción “Index” a una API, es cuando se llama a un tipo de datos sin especificar un registro. Lo que hace que el API regrese la lista completa de registros de ese tipo a la que el usuario tiene acceso.

**Comment by jriverac** [comment]
En esta es donde quiero que jales todos los registros del API y los pongamos en una **TableView**.

**Comment by LaurentinoMX** [comment]
Estoy revisando documentación de como trabaja el TableView con la clase IUTableView eldia de hoy empece a estudiarla, el día de mañana empezare a codificar

**Comment by jriverac** [comment]
No olvides tu mantra del buen developer (!= IBM Developer): “Commit early, commit often.”
